# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180508_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
